DROP DATABASE Lubian;

CREATE DATABASE Lubian;

USE Lubian;

CREATE TABLE user(
	id BIGINT(19) PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(25) NOT NULL UNIQUE
) AUTO_INCREMENT = 1001;

CREATE TABLE todo(
	id BIGINT(19) PRIMARY KEY AUTO_INCREMENT,
    body VARCHAR(255) NOT NULL
) AUTO_INCREMENT = 1001;